### ISSUE TITLE
zendframework/zend-diactoros is abandoned

### ISSUE THREAD

**Issue by alexanderschnitzler** [meng-tian/soap-http-binding#2]
Hi, 
composer tells me that `zendframework/zend-diactoros` is abandoned and should be replaced.

`Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.`

Any plans to replace that package? And is this package still actively maintained?

Thanks in advance.

**Comment by realmtian** [comment]
Hi Alexander,

Thanks for letting me know.

Given both `zendframework/zend-diactoros` and `laminas/laminas-diactoros` are implementing the same interface, i.e., PSR-7, it shouldn't be a huge task to replace the abandoned one.

I will try do the refactoring this week.

**Comment by alexanderschnitzler** [comment]
Hi Meng,
don't feel pushed. Take your time. If I find some time myself before you do I will create a PR. :)
